version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
permissions:
  - object: /var/www/html/
    mode: 755
    pattern: "**"
    owner: root    
hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: root
    - location: start_server.sh
      timeout: 300
      runas: root
 
